namespace WealthLedger.Api.Contracts;

public sealed record PhysicalGoldCostRequest(
    string TypeCode,
    string TreatmentCode,
    long AmountMinorUnits,
    string CurrencyCode,
    string? Note = null);

public sealed record PhysicalGoldSelectedLotRequest(
    Guid AssetLotId,
    long GrossWeightRawE8,
    int PieceCount);

public sealed record PhysicalGoldPurchaseRequest(
    Guid HouseholdId,
    Guid PortfolioId,
    Guid GoldAccountId,
    Guid CashAccountId,
    Guid GoldAssetId,
    Guid CashAssetId,
    long GrossWeightRawE8,
    int FinenessPpm,
    int PieceCount,
    long CashConsiderationMinorUnits,
    string CashConsiderationCurrencyCode,
    DateOnly ExecutionDate,
    long? ExecutedUnitPriceRawE8 = null,
    string? PriceCurrencyCode = null,
    Guid? CounterpartyInstitutionId = null,
    DateOnly? OrderDate = null,
    DateOnly? SettlementDate = null,
    IReadOnlyList<PhysicalGoldCostRequest>? Costs = null,
    string? Hallmark = null,
    string? CertificateReference = null,
    string? LotNote = null,
    string? ExternalReference = null,
    string? Note = null);

public sealed record PhysicalGoldSaleRequest(
    Guid HouseholdId,
    Guid PortfolioId,
    Guid GoldAccountId,
    Guid CashAccountId,
    Guid GoldAssetId,
    Guid CashAssetId,
    long GrossWeightRawE8,
    int PieceCount,
    IReadOnlyList<PhysicalGoldSelectedLotRequest>? SelectedLots,
    long CashConsiderationMinorUnits,
    string CashConsiderationCurrencyCode,
    DateOnly ExecutionDate,
    long? ExecutedUnitPriceRawE8 = null,
    string? PriceCurrencyCode = null,
    Guid? CounterpartyInstitutionId = null,
    DateOnly? OrderDate = null,
    DateOnly? SettlementDate = null,
    IReadOnlyList<PhysicalGoldCostRequest>? Costs = null,
    string? ExternalReference = null,
    string? Note = null,
    string? ReviewedPlanFingerprint = null);

public sealed record PhysicalGoldTransferRequest(
    Guid HouseholdId,
    Guid SourcePortfolioId,
    Guid SourceGoldAccountId,
    Guid DestinationPortfolioId,
    Guid DestinationGoldAccountId,
    Guid GoldAssetId,
    long GrossWeightRawE8,
    int PieceCount,
    IReadOnlyList<PhysicalGoldSelectedLotRequest>? SelectedLots,
    DateOnly ExecutionDate,
    Guid? CashPortfolioId = null,
    Guid? CashAccountId = null,
    Guid? CashAssetId = null,
    IReadOnlyList<PhysicalGoldCostRequest>? Costs = null,
    string? ExternalReference = null,
    string? Note = null,
    string? ReviewedPlanFingerprint = null);

public sealed record PhysicalGoldEconomicsResponse(
    long? CashConsiderationMinorUnits,
    long AdditionalCashOutflowMinorUnits,
    long IncludedInConsiderationMinorUnits,
    long WithheldFromProceedsMinorUnits,
    long InformationalOnlyMinorUnits,
    long AdditionalFeeMinorUnits,
    long AdditionalTaxMinorUnits,
    long NetCashEffectMinorUnits,
    long? PriceImpliedGrossMinorUnits,
    bool PriceImpliedGrossIsRounded,
    long? ExpectedConsiderationMinorUnits,
    long? DiscrepancyMinorUnits,
    string DiscrepancyCode,
    long? AcquisitionLotCostMinorUnits,
    string CurrencyCode);

public sealed record PhysicalGoldCostResponse(
    string TypeCode,
    string TreatmentCode,
    long AmountMinorUnits,
    string CurrencyCode,
    string? Note);

public sealed record PhysicalGoldPlanLineResponse(
    Guid AssetLotId,
    DateOnly? AcquiredOn,
    long AvailableGrossWeightRawE8,
    int AvailablePieceCount,
    long MovedGrossWeightRawE8,
    int MovedPieceCount,
    long RemainingGrossWeightRawE8,
    int RemainingPieceCount,
    int FinenessPpm,
    decimal MovedFineWeightGrams,
    string CostStatusCode,
    long? LotCostMinorUnits,
    string? LotCostCurrencyCode,
    string? Hallmark,
    string? CertificateReference);

public sealed record PhysicalGoldRealizedCostAmountResponse(
    string CurrencyCode,
    long MinorUnits);

public sealed record PhysicalGoldRealizedCostLotLineResponse(
    Guid AssetLotId,
    long QuantityRawE8,
    string CostStatusCode,
    long? KnownCostMinorUnits,
    string? KnownCostCurrencyCode);

public sealed record PhysicalGoldRealizedCostResponse(
    string CompletenessCode,
    long KnownQuantityRawE8,
    long UnknownQuantityRawE8,
    IReadOnlyList<PhysicalGoldRealizedCostAmountResponse> KnownAmounts,
    IReadOnlyList<PhysicalGoldRealizedCostLotLineResponse> Lines,
    string MethodCode,
    DateTimeOffset? DerivedAtUtc = null,
    bool? SourceSaleIsEffective = null);

public sealed record PhysicalGoldPurchasePreviewResponse(
    Guid HouseholdId,
    Guid PortfolioId,
    string PortfolioName,
    Guid GoldAccountId,
    string GoldAccountName,
    Guid CashAccountId,
    string CashAccountName,
    Guid GoldAssetId,
    string GoldAssetCode,
    string GoldAssetName,
    Guid CashAssetId,
    string CurrencyCode,
    int MinorUnitDigits,
    DateOnly ExecutionDate,
    DateOnly? OrderDate,
    DateOnly? SettlementDate,
    long GrossWeightRawE8,
    int FinenessPpm,
    decimal FineWeightGrams,
    int PieceCount,
    long? ExecutedUnitPriceRawE8,
    Guid? CounterpartyInstitutionId,
    string? CounterpartyName,
    PhysicalGoldEconomicsResponse Economics,
    IReadOnlyList<PhysicalGoldCostResponse> Costs,
    string? Hallmark,
    string? CertificateReference,
    string? LotNote,
    string? ExternalReference,
    string? Note,
    IReadOnlyList<string> WarningCodes);

public sealed record PhysicalGoldSalePreviewResponse(
    Guid HouseholdId,
    Guid PortfolioId,
    string PortfolioName,
    Guid GoldAccountId,
    string GoldAccountName,
    Guid CashAccountId,
    string CashAccountName,
    Guid GoldAssetId,
    string GoldAssetCode,
    string GoldAssetName,
    Guid CashAssetId,
    string CurrencyCode,
    int MinorUnitDigits,
    DateOnly ExecutionDate,
    DateOnly? OrderDate,
    DateOnly? SettlementDate,
    long GrossWeightRawE8,
    int PieceCount,
    long? ExecutedUnitPriceRawE8,
    Guid? CounterpartyInstitutionId,
    string? CounterpartyName,
    PhysicalGoldEconomicsResponse Economics,
    IReadOnlyList<PhysicalGoldCostResponse> Costs,
    IReadOnlyList<PhysicalGoldPlanLineResponse> Plan,
    string PlanFingerprint,
    PhysicalGoldRealizedCostResponse RealizedCost,
    string? ExternalReference,
    string? Note,
    IReadOnlyList<string> WarningCodes);

public sealed record PhysicalGoldTransferPreviewResponse(
    Guid HouseholdId,
    Guid SourcePortfolioId,
    string SourcePortfolioName,
    Guid SourceGoldAccountId,
    string SourceGoldAccountName,
    Guid DestinationPortfolioId,
    string DestinationPortfolioName,
    Guid DestinationGoldAccountId,
    string DestinationGoldAccountName,
    Guid GoldAssetId,
    string GoldAssetCode,
    string GoldAssetName,
    string CurrencyCode,
    int MinorUnitDigits,
    DateOnly ExecutionDate,
    long GrossWeightRawE8,
    int PieceCount,
    decimal FineWeightGrams,
    PhysicalGoldEconomicsResponse Economics,
    IReadOnlyList<PhysicalGoldCostResponse> Costs,
    IReadOnlyList<PhysicalGoldPlanLineResponse> Plan,
    string PlanFingerprint,
    string? ExternalReference,
    string? Note,
    IReadOnlyList<string> WarningCodes);

public sealed record RecordPhysicalGoldActivityResponse(
    Guid TransactionId,
    Guid? AssetLotId,
    string TransactionLocation,
    string VerificationLocation);

public sealed record PhysicalGoldAllocationResponse(
    Guid AssetLotId,
    Guid AllocationId,
    Guid PortfolioId,
    string PortfolioName,
    Guid AccountId,
    string AccountName,
    long GrossWeightDeltaRawE8,
    int PieceDelta,
    DateOnly? AcquiredOn,
    string CostStatusCode,
    long? LotCostMinorUnits,
    string? LotCostCurrencyCode,
    int FinenessPpm,
    int OriginalPieceCount,
    string? Hallmark,
    string? CertificateReference,
    string? LotNote,
    decimal FineWeightDeltaGrams);

public sealed record PhysicalGoldCustodyPositionResponse(
    Guid PortfolioId,
    string PortfolioName,
    Guid AccountId,
    string AccountName,
    Guid GoldAssetId,
    string GoldAssetCode,
    string GoldAssetName,
    Guid AssetLotId,
    long GrossWeightRawE8,
    int PieceCount,
    int FinenessPpm,
    decimal FineWeightGrams,
    DateOnly? AcquiredOn,
    string CostStatusCode,
    long? CostMinorUnits,
    string? CostCurrencyCode,
    string? Hallmark,
    string? CertificateReference);

public sealed record PhysicalGoldActivityVerificationResponse(
    Guid TransactionId,
    Guid HouseholdId,
    string TransactionTypeCode,
    string StatusCode,
    DateOnly? OrderDate,
    DateOnly ExecutionDate,
    DateOnly? SettlementDate,
    DateTimeOffset PostedAtUtc,
    string? ExternalReference,
    string? Note,
    Guid? ReversedByTransactionId,
    Guid GoldAssetId,
    string GoldAssetCode,
    string GoldAssetName,
    Guid? CashAssetId,
    string CurrencyCode,
    int MinorUnitDigits,
    Guid? CounterpartyInstitutionId,
    string? CounterpartyName,
    long GrossWeightRawE8,
    int PieceCount,
    long? ExecutedUnitPriceRawE8,
    string? PriceCurrencyCode,
    long? CashConsiderationMinorUnits,
    Guid? CreatedAssetLotId,
    PhysicalGoldEconomicsResponse Economics,
    IReadOnlyList<PhysicalGoldCostResponse> Costs,
    IReadOnlyList<PhysicalGoldAllocationResponse> Allocations,
    IReadOnlyList<PhysicalGoldCustodyPositionResponse> CurrentCustody,
    PhysicalGoldRealizedCostResponse? RealizedCost,
    IReadOnlyList<string> WarningCodes);

public sealed record PhysicalGoldCustodyInventoryResponse(
    Guid HouseholdId,
    IReadOnlyList<PhysicalGoldCustodyPositionResponse> Items);
