// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WealthLedger.Infrastructure.Persistence;

#nullable disable

namespace WealthLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WealthLedgerDbContext))]
    partial class WealthLedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.AccountRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseholdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("AccountTypeCode");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("HouseholdId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Account_Household_Code");

                    b.ToTable("Account", null, t =>
                        {
                            t.HasCheckConstraint("CK_Account_DateOrder", "\"OpenedOn\" IS NULL OR \"ClosedOn\" IS NULL OR \"OpenedOn\" <= \"ClosedOn\"");

                            t.HasCheckConstraint("CK_Account_IsActive", "\"IsActive\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Account_Type", "\"AccountTypeCode\" IN ('CASH', 'INVESTMENT', 'PHYSICAL_VAULT', 'PENSION', 'PROPERTY_REGISTRY', 'OTHER')");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.AssetLotRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcquiredOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CostBasisCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("CostBasisStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("CostBasisStatusCode");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningTransactionEntryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OriginalCostBasisMinor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CostBasisCurrencyCode");

                    b.HasIndex("OpeningTransactionEntryId");

                    b.HasIndex("AssetId", "AcquiredOn")
                        .HasDatabaseName("IX_AssetLot_Asset_Date");

                    b.ToTable("AssetLot", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssetLot_CostBasisAmount", "\"OriginalCostBasisMinor\" IS NULL OR \"OriginalCostBasisMinor\" >= 0");

                            t.HasCheckConstraint("CK_AssetLot_CostBasisShape", "(\"CostBasisStatusCode\" = 'KNOWN' AND \"OriginalCostBasisMinor\" IS NOT NULL AND \"CostBasisCurrencyCode\" IS NOT NULL) OR (\"CostBasisStatusCode\" IN ('UNKNOWN', 'NOT_APPLICABLE') AND \"OriginalCostBasisMinor\" IS NULL AND \"CostBasisCurrencyCode\" IS NULL)");

                            t.HasCheckConstraint("CK_AssetLot_CostBasisStatus", "\"CostBasisStatusCode\" IN ('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE')");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.AssetRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("BaseUnitCode");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LotTrackingMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("LotTrackingModeCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("AssetTypeCode");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyCode");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Asset_Code");

                    b.ToTable("Asset", null, t =>
                        {
                            t.HasCheckConstraint("CK_Asset_BaseUnit", "\"BaseUnitCode\" IN ('CURRENCY_UNIT', 'FUND_UNIT', 'SHARE', 'GROSS_GRAM', 'PIECE', 'PROPERTY', 'LAND_PARCEL', 'VEHICLE', 'OTHER')");

                            t.HasCheckConstraint("CK_Asset_IsActive", "\"IsActive\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Asset_LotTrackingMode", "\"LotTrackingModeCode\" IN ('NONE', 'OPTIONAL', 'REQUIRED')");

                            t.HasCheckConstraint("CK_Asset_Type", "\"AssetTypeCode\" IN ('CASH', 'CURRENCY', 'FUND', 'EQUITY', 'PHYSICAL_GOLD', 'REAL_ESTATE', 'LAND', 'VEHICLE', 'OTHER')");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.CashFlowDetailRow", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("CashFlowCategoryCode");

                    b.Property<string>("HouseholdMemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("HouseholdMemberId");

                    b.ToTable("CashFlowDetail", null, t =>
                        {
                            t.HasCheckConstraint("CK_CashFlowDetail_Category", "\"CashFlowCategoryCode\" IN ('SALARY', 'BONUS', 'ACADEMIC_INCOME', 'GIFT', 'EXTERNAL_SALE', 'OTHER')");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.CurrencyRow", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinorUnitDigits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Currency", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currency_Code", "length(\"Code\") = 3 AND \"Code\" GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_Currency_MinorUnitDigits", "\"MinorUnitDigits\" BETWEEN 0 AND 8");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.HouseholdMemberRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseholdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("IX_HouseholdMember_Household");

                    b.ToTable("HouseholdMember", null, t =>
                        {
                            t.HasCheckConstraint("CK_HouseholdMember_IsActive", "\"IsActive\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.HouseholdRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyCode");

                    b.ToTable("Household", (string)null);
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.InstitutionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("InstitutionTypeCode");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Institution_Code");

                    b.ToTable("Institution", null, t =>
                        {
                            t.HasCheckConstraint("CK_Institution_IsActive", "\"IsActive\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Institution_Type", "\"InstitutionTypeCode\" IN ('BANK', 'BROKER', 'ASSET_MANAGER', 'JEWELER', 'PENSION', 'OTHER')");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.LedgerTransactionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseholdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReversalOfTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettlementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("StatusCode");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("TransactionTypeCode");

                    b.HasKey("Id");

                    b.HasIndex("ReversalOfTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_LedgerTransaction_Reversal")
                        .HasFilter("\"ReversalOfTransactionId\" IS NOT NULL");

                    b.HasIndex("HouseholdId", "Status", "ExecutionDate")
                        .HasDatabaseName("IX_LedgerTransaction_Household_Status_Date");

                    b.ToTable("LedgerTransaction", null, t =>
                        {
                            t.HasCheckConstraint("CK_LedgerTransaction_ExecutionSettlementDate", "\"ExecutionDate\" IS NULL OR \"SettlementDate\" IS NULL OR \"ExecutionDate\" <= \"SettlementDate\"");

                            t.HasCheckConstraint("CK_LedgerTransaction_OrderExecutionDate", "\"OrderDate\" IS NULL OR \"ExecutionDate\" IS NULL OR \"OrderDate\" <= \"ExecutionDate\"");

                            t.HasCheckConstraint("CK_LedgerTransaction_Ordered", "\"StatusCode\" <> 'ORDERED' OR (\"TransactionTypeCode\" IN ('BUY', 'SELL') AND \"OrderDate\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_LedgerTransaction_PostedAt", "(\"StatusCode\" = 'POSTED' AND \"PostedAtUtc\" IS NOT NULL) OR (\"StatusCode\" <> 'POSTED' AND \"PostedAtUtc\" IS NULL)");

                            t.HasCheckConstraint("CK_LedgerTransaction_ReversalShape", "(\"TransactionTypeCode\" = 'REVERSAL' AND \"ReversalOfTransactionId\" IS NOT NULL) OR (\"TransactionTypeCode\" <> 'REVERSAL' AND \"ReversalOfTransactionId\" IS NULL)");

                            t.HasCheckConstraint("CK_LedgerTransaction_ReversalTarget", "\"ReversalOfTransactionId\" IS NULL OR \"ReversalOfTransactionId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_LedgerTransaction_Status", "\"StatusCode\" IN ('DRAFT', 'ORDERED', 'POSTED', 'CANCELLED')");

                            t.HasCheckConstraint("CK_LedgerTransaction_Type", "\"TransactionTypeCode\" IN ('CONTRIBUTION', 'WITHDRAWAL', 'BUY', 'SELL', 'TRANSFER', 'DIVIDEND', 'INCOME', 'EXPENSE', 'FEE', 'TAX', 'CORPORATE_ACTION', 'OPENING_BALANCE', 'ADJUSTMENT', 'REVERSAL')");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.LotEntryAllocationRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetLotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityDeltaE8")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionEntryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetLotId")
                        .HasDatabaseName("IX_LotEntryAllocation_Lot");

                    b.HasIndex("TransactionEntryId")
                        .HasDatabaseName("IX_LotEntryAllocation_Entry");

                    b.HasIndex("AssetLotId", "TransactionEntryId")
                        .IsUnique()
                        .HasDatabaseName("UX_LotEntryAllocation_Lot_Entry");

                    b.ToTable("LotEntryAllocation", null, t =>
                        {
                            t.HasCheckConstraint("CK_LotEntryAllocation_Quantity", "\"QuantityDeltaE8\" <> 0");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.PhysicalGoldLotDetailRow", b =>
                {
                    b.Property<string>("AssetLotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActualFinenessPpm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateReference")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hallmark")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetLotId");

                    b.ToTable("PhysicalGoldLotDetail", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhysicalGoldLotDetail_Fineness", "\"ActualFinenessPpm\" > 0 AND \"ActualFinenessPpm\" <= 1000000");

                            t.HasCheckConstraint("CK_PhysicalGoldLotDetail_PieceCount", "\"PieceCount\" > 0");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.PortfolioRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseholdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("StatusCode");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Portfolio_Household_Code");

                    b.ToTable("Portfolio", null, t =>
                        {
                            t.HasCheckConstraint("CK_Portfolio_ClosedAt", "(\"StatusCode\" = 'ACTIVE' AND \"ClosedAtUtc\" IS NULL) OR (\"StatusCode\" IN ('CLOSED', 'ARCHIVED') AND \"ClosedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Portfolio_Status", "\"StatusCode\" IN ('ACTIVE', 'CLOSED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.TransactionCostComponentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("TreatmentCode");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("CostTypeCode");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_TransactionCostComponent_Transaction");

                    b.ToTable("TransactionCostComponent", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransactionCostComponent_Amount", "\"AmountMinor\" >= 0");

                            t.HasCheckConstraint("CK_TransactionCostComponent_Treatment", "\"TreatmentCode\" IN ('ADDITIONAL_CASH_OUTFLOW', 'WITHHELD_FROM_PROCEEDS', 'INCLUDED_IN_CONSIDERATION', 'INFORMATIONAL_ONLY')");

                            t.HasCheckConstraint("CK_TransactionCostComponent_Type", "\"CostTypeCode\" IN ('COMMISSION', 'WITHHOLDING_TAX', 'OTHER_TAX', 'MAKING_CHARGE', 'BROKERAGE', 'TITLE_DEED', 'EXPERTISE', 'NOTARY', 'INSURANCE', 'OTHER')");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.TransactionEntryRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityDeltaE8")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("EntryRoleCode");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UnitPriceE8")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PriceCurrencyCode");

                    b.HasIndex("AccountId", "AssetId")
                        .HasDatabaseName("IX_TransactionEntry_Account_Asset");

                    b.HasIndex("PortfolioId", "AssetId")
                        .HasDatabaseName("IX_TransactionEntry_Portfolio_Asset");

                    b.HasIndex("TransactionId", "EntrySequence")
                        .IsUnique()
                        .HasDatabaseName("UX_TransactionEntry_Transaction_Sequence");

                    b.ToTable("TransactionEntry", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransactionEntry_Quantity", "\"QuantityDeltaE8\" <> 0");

                            t.HasCheckConstraint("CK_TransactionEntry_Role", "\"EntryRoleCode\" IN ('PRINCIPAL', 'CONSIDERATION', 'TRANSFER', 'INCOME', 'FEE', 'TAX', 'ADJUSTMENT')");

                            t.HasCheckConstraint("CK_TransactionEntry_Sequence", "\"EntrySequence\" >= 0");

                            t.HasCheckConstraint("CK_TransactionEntry_UnitPrice", "\"UnitPriceE8\" IS NULL OR \"UnitPriceE8\" >= 0");

                            t.HasCheckConstraint("CK_TransactionEntry_UnitPriceCurrency", "(\"UnitPriceE8\" IS NULL AND \"PriceCurrencyCode\" IS NULL) OR (\"UnitPriceE8\" IS NOT NULL AND \"PriceCurrencyCode\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.AccountRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.HouseholdRow", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.InstitutionRow", null)
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.AssetLotRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.CurrencyRow", null)
                        .WithMany()
                        .HasForeignKey("CostBasisCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.TransactionEntryRow", null)
                        .WithMany()
                        .HasForeignKey("OpeningTransactionEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.AssetRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.CurrencyRow", null)
                        .WithMany()
                        .HasForeignKey("BaseCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.CashFlowDetailRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.HouseholdMemberRow", null)
                        .WithMany()
                        .HasForeignKey("HouseholdMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.LedgerTransactionRow", null)
                        .WithOne()
                        .HasForeignKey("WealthLedger.Infrastructure.Persistence.Rows.CashFlowDetailRow", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.HouseholdMemberRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.HouseholdRow", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.HouseholdRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.CurrencyRow", null)
                        .WithMany()
                        .HasForeignKey("BaseCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.LedgerTransactionRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.HouseholdRow", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.LedgerTransactionRow", null)
                        .WithMany()
                        .HasForeignKey("ReversalOfTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.LotEntryAllocationRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.AssetLotRow", null)
                        .WithMany()
                        .HasForeignKey("AssetLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.TransactionEntryRow", null)
                        .WithMany()
                        .HasForeignKey("TransactionEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.PhysicalGoldLotDetailRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.AssetLotRow", null)
                        .WithOne()
                        .HasForeignKey("WealthLedger.Infrastructure.Persistence.Rows.PhysicalGoldLotDetailRow", "AssetLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.PortfolioRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.HouseholdRow", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.TransactionCostComponentRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.CurrencyRow", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.LedgerTransactionRow", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WealthLedger.Infrastructure.Persistence.Rows.TransactionEntryRow", b =>
                {
                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.PortfolioRow", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.CurrencyRow", null)
                        .WithMany()
                        .HasForeignKey("PriceCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WealthLedger.Infrastructure.Persistence.Rows.LedgerTransactionRow", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
